---
# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "backstage-rw"
  CATALOG_LOCATION: "https://github.com/dirien/backstage-demo/blob/main/catalog/catalog-all.yaml"
  BASE_URL: "backstage.74.220.20.178.nip.io"
  ARGOCD_URL: "http://argocd.74.220.20.178.nip.io/api/v1/"
